import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer'
import type { Checklist, ChecklistCategory } from '@/lib/db'

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: '#f43f5e',
    paddingBottom: 16,
  },
  title: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    color: '#0a0a0f',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 11,
    color: '#71717a',
  },
  category: {
    marginBottom: 20,
  },
  categoryHeader: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: '#f43f5e',
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#fce7f3',
  },
  item: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
    paddingLeft: 8,
  },
  checkbox: {
    width: 12,
    height: 12,
    borderWidth: 1,
    borderColor: '#f43f5e',
    borderRadius: 2,
    marginRight: 8,
    marginTop: 1,
  },
  checkboxCompleted: {
    width: 12,
    height: 12,
    borderWidth: 1,
    borderColor: '#f43f5e',
    borderRadius: 2,
    marginRight: 8,
    marginTop: 1,
    backgroundColor: '#f43f5e',
  },
  itemText: {
    fontSize: 10,
    color: '#27272a',
    flex: 1,
    lineHeight: 1.5,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 9,
    color: '#a1a1aa',
    borderTopWidth: 1,
    borderTopColor: '#f4f4f5',
    paddingTop: 12,
  },
})

interface ChecklistPDFProps {
  checklist: Checklist
}

export function ChecklistPDF({ checklist }: ChecklistPDFProps) {
  const categories = checklist.categories as ChecklistCategory[]

  const formattedDate = new Date(checklist.created_at).toLocaleDateString(
    'en-US',
    {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }
  )

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>
            BreakupBox — Your Digital Untangling Checklist
          </Text>
          <Text style={styles.subtitle}>Generated on {formattedDate}</Text>
        </View>

        {categories.map((cat) => (
          <View key={cat.id} style={styles.category} wrap={false}>
            <Text style={styles.categoryHeader}>
              {cat.icon} {cat.name}
            </Text>
            {cat.items.map((item) => (
              <View key={item.id} style={styles.item}>
                <View
                  style={
                    item.completed ? styles.checkboxCompleted : styles.checkbox
                  }
                />
                <Text style={styles.itemText}>{item.text}</Text>
              </View>
            ))}
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by BreakupBox — breakupbox.app | Take care of yourself 💔
        </Text>
      </Page>
    </Document>
  )
}
